import { 
  Partner, 
  Lead, 
  Offer, 
  Earning, 
  PayoutRequest, 
  CommissionPlan, 
  Tier, 
  ProgramSettings, 
  AuditLog, 
  RewardClaim
} from "./types";

export const initialCommissionPlans: CommissionPlan[] = [
  {
    id: "plan-1",
    name: "Standard Growth Plan (Recurring 12M)",
    description: "20% commission on every monthly subscription for the first 12 months",
    type: "recurring_n_months",
    percentageRate: 20,
    monthsCount: 12,
    holdPeriodDays: 30,
    qualifyingStatus: "paid",
    active: true,
    version: 1,
    workedExample: "A brand paying ₹10,000/mo earns you ₹2,000/mo for 12 months (Total ₹24,000)",
  },
  {
    id: "plan-2",
    name: "Enterprise Flat Bounty",
    description: "₹15,000 fixed bounty on brand onboarding",
    type: "fixed_per_client",
    fixedAmountPaise: 1500000,
    holdPeriodDays: 14,
    qualifyingStatus: "onboarded",
    active: true,
    version: 1,
    workedExample: "Any enterprise brand that onboards pays you a flat ₹15,000 instantly",
  },
  {
    id: "plan-3",
    name: "Gold Partner Tier Plan",
    description: "15% lifetime recurring commission on all referred brands",
    type: "recurring_lifetime",
    percentageRate: 15,
    holdPeriodDays: 30,
    qualifyingStatus: "paid",
    active: true,
    version: 2,
    workedExample: "Earn 15% on every renewal as long as the brand remains an active Retner subscriber",
  },
  {
    id: "plan-4",
    name: "Hybrid Accelerator",
    description: "₹5,000 upfront bonus + 10% recurring for 6 months",
    type: "hybrid",
    fixedAmountPaise: 500000,
    percentageRate: 10,
    monthsCount: 6,
    holdPeriodDays: 30,
    qualifyingStatus: "paid",
    active: true,
    version: 1,
    workedExample: "₹5,000 cash on first bill + ₹1,000/mo on a ₹10,000 plan for 6 months",
  }
];

export const initialTiers: Tier[] = [
  {
    id: "tier-silver",
    name: "Silver Partner",
    order: 1,
    badgeColor: "#94A3B8",
    iconName: "Shield",
    thresholdMetric: "paid_referrals",
    thresholdValue: 0,
    linkedPlanId: "plan-1",
    perks: ["10% Standard Commission", "Self-serve Partner Dashboard", "Standard email support"],
  },
  {
    id: "tier-gold",
    name: "Gold Partner",
    order: 2,
    badgeColor: "#F59E0B",
    iconName: "Award",
    thresholdMetric: "paid_referrals",
    thresholdValue: 5,
    linkedPlanId: "plan-3",
    perks: ["15% Lifetime Commission", "Priority WhatsApp support", "Early access to feature roadmaps", "Higher offer rewards"],
  },
  {
    id: "tier-platinum",
    name: "Platinum Elite",
    order: 3,
    badgeColor: "#8B5CF6",
    iconName: "Crown",
    thresholdMetric: "paid_referrals",
    thresholdValue: 15,
    linkedPlanId: "plan-4",
    perks: ["20% Lifetime Commission", "Dedicated Partner Manager", "Co-marketing webinars & case studies", "VIP physical gifting rail"],
  },
];

export const initialOffers: Offer[] = [
  {
    id: "off-1",
    title: "AirPods Pro Milestone",
    subtitle: "Refer 3 paid clients this month",
    badgeText: "HOT REWARD",
    description: "Refer 3 D2C brands that convert to paid Retner plans and get Apple AirPods Pro (2nd Gen) delivered to your doorstep.",
    heroImage: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&auto=format&fit=crop&q=80",
    rewardType: "milestone_gift",
    rewardName: "Apple AirPods Pro (2nd Gen)",
    rewardValuePaise: 2490000,
    targetCount: 3,
    targetStatus: "paid",
    windowOnly: true,
    startAt: "2026-09-01T00:00:00Z",
    endAt: "2026-12-31T23:59:59Z",
    status: "live",
    eligibleTiers: ["tier-silver", "tier-gold", "tier-platinum"],
    terms: "Brand must be active for at least 7 days. Limit 1 claim per agency. Shipping within India only.",
    featured: true,
    userProgress: 0,
    unlocked: false,
  },
  {
    id: "off-2",
    title: "₹5,000 Festive Cash Bonus",
    subtitle: "Direct credit to your earnings ledger",
    badgeText: "SPECIAL BONUS",
    description: "Close 2 paid brand referrals and receive an extra ₹5,000 cash bonus directly in your withdrawable balance.",
    heroImage: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&auto=format&fit=crop&q=80",
    rewardType: "cash_bonus",
    rewardName: "₹5,000 Ledger Credit",
    rewardValuePaise: 500000,
    targetCount: 2,
    targetStatus: "paid",
    windowOnly: false,
    startAt: "2026-09-15T00:00:00Z",
    endAt: "2026-12-31T23:59:59Z",
    status: "live",
    eligibleTiers: ["tier-silver", "tier-gold", "tier-platinum"],
    terms: "Stacks with standard tier commission rates. Standard 30-day hold applies.",
    featured: true,
    userProgress: 0,
    unlocked: false,
  },
  {
    id: "off-3",
    title: "₹2,000 Amazon Voucher",
    subtitle: "Instant digital code on 1st referral",
    badgeText: "FAST UNLOCK",
    description: "Get your first brand to book a demo and start their trial to instantly claim a ₹2,000 Amazon shopping gift card.",
    heroImage: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&auto=format&fit=crop&q=80",
    rewardType: "voucher",
    rewardName: "Amazon ₹2,000 E-Voucher",
    rewardValuePaise: 200000,
    targetCount: 1,
    targetStatus: "demo_booked",
    windowOnly: false,
    startAt: "2026-08-01T00:00:00Z",
    endAt: "2026-12-31T23:59:59Z",
    status: "live",
    eligibleTiers: ["tier-silver", "tier-gold", "tier-platinum"],
    terms: "Voucher code sent instantly via WhatsApp and Email upon claim.",
    featured: false,
    userProgress: 0,
    unlocked: false,
  },
];

export const initialSettings: ProgramSettings = {
  attributionWindowDays: 60,
  leadProtectionDays: 90,
  autoApprovePartners: false,
  defaultHoldDays: 30,
  minPayoutPaise: 100000,
  maxOpenPayouts: 1,
  tdsRatePercent: 5.0,
  tdsAnnualThresholdPaise: 1500000,
  notificationAlertEmails: ["partners@retner.ai", "finance@retner.ai"],
};

// Clean initial data (No hardcoded dummy records)
export const initialPartners: Partner[] = [];
export const initialLeads: Lead[] = [];
export const initialEarnings: Earning[] = [];
export const initialPayouts: PayoutRequest[] = [];
export const initialRewardClaims: RewardClaim[] = [];
export const initialAuditLogs: AuditLog[] = [];
