import { 
  Partner, 
  Lead, 
  Offer, 
  Earning, 
  PayoutRequest, 
  CommissionPlan, 
  Tier, 
  ProgramSettings, 
  AuditLog, 
  RewardClaim
} from "./types";

export const initialCommissionPlans: CommissionPlan[] = [
  {
    id: "plan-diwali-15",
    name: "Tier 1: 15% 12-Month Revenue Share",
    description: "15% of net subscription revenue for 12 months per client (Clients 1 to 4)",
    type: "recurring_n_months",
    percentageRate: 15,
    monthsCount: 12,
    holdPeriodDays: 30,
    qualifyingStatus: "paid",
    active: true,
    version: 1,
    workedExample: "On ₹3,500/mo plan (₹42,000/yr), earn ₹6,300/year per client (₹1,575/quarter).",
  },
  {
    id: "plan-diwali-20",
    name: "Tier 2: 20% 12-Month Revenue Share",
    description: "20% of net subscription revenue for 12 months per client (Clients 5 to 9)",
    type: "recurring_n_months",
    percentageRate: 20,
    monthsCount: 12,
    holdPeriodDays: 30,
    qualifyingStatus: "paid",
    active: true,
    version: 1,
    workedExample: "On ₹3,500/mo plan (₹42,000/yr), earn ₹8,400/year per client (₹2,100/quarter).",
  },
  {
    id: "plan-diwali-25",
    name: "Tier 3: 25% 12-Month Revenue Share",
    description: "25% of net subscription revenue for 12 months per client (Client 10+)",
    type: "recurring_n_months",
    percentageRate: 25,
    monthsCount: 12,
    holdPeriodDays: 30,
    qualifyingStatus: "paid",
    active: true,
    version: 1,
    workedExample: "On ₹3,500/mo plan (₹42,000/yr), earn ₹10,500/year per client (₹2,625/quarter).",
  }
];

export const initialTiers: Tier[] = [
  {
    id: "tier-silver",
    name: "Silver (15% Share)",
    order: 1,
    badgeColor: "#94A3B8",
    iconName: "Shield",
    thresholdMetric: "paid_referrals",
    thresholdValue: 0,
    linkedPlanId: "plan-diwali-15",
    perks: [
      "15% 12-Month Revenue Share on Clients 1-4",
      "Fast-Start Cash Bonus eligible (up to ₹4,000)",
      "90-Day Lead Attribution Lock",
      "Self-Serve Partner Dashboard & Collaterals"
    ],
  },
  {
    id: "tier-gold",
    name: "Gold (20% Share)",
    order: 2,
    badgeColor: "#F59E0B",
    iconName: "Award",
    thresholdMetric: "paid_referrals",
    thresholdValue: 5,
    linkedPlanId: "plan-diwali-20",
    perks: [
      "20% 12-Month Revenue Share on Clients 5-9",
      "Diya Milestone Gift eligible (₹3,000 Amazon Voucher)",
      "Partner Circle Badge & Directory Listing",
      "Priority WhatsApp Support"
    ],
  },
  {
    id: "tier-platinum",
    name: "Platinum Elite (25% Share)",
    order: 3,
    badgeColor: "#8B5CF6",
    iconName: "Crown",
    thresholdMetric: "paid_referrals",
    thresholdValue: 10,
    linkedPlanId: "plan-diwali-25",
    perks: [
      "25% 12-Month Revenue Share on Client 10+",
      "Lantern & Firework Milestone Gifts eligible (₹15,000 Voucher / AirPods)",
      "Co-branded Case Studies on Retner Channels",
      "VIP Dedicated Partner Manager & Priority Line"
    ],
  },
];

export const initialOffers: Offer[] = [
  {
    id: "off-faststart",
    title: "Fast-Start Cash Bonus",
    subtitle: "Up to ₹4,000 cash for first 3 referrals",
    badgeText: "FAST-START",
    description: "Earn ₹2,000 for your 1st paid referral, and ₹1,000 each for your 2nd and 3rd within the 30-day fast-start window. Disbursed within 7 working days of cleared payment.",
    heroImage: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&auto=format&fit=crop&q=80",
    rewardType: "cash_bonus",
    rewardName: "₹4,000 Fast-Start Cash (₹2k + ₹1k + ₹1k)",
    rewardValuePaise: 400000,
    targetCount: 1,
    targetStatus: "paid",
    windowOnly: true,
    startAt: "2026-09-01T00:00:00Z",
    endAt: "2026-12-31T23:59:59Z",
    status: "live",
    eligibleTiers: ["tier-silver", "tier-gold", "tier-platinum"],
    terms: "First payment cleared within 30-day window. Paid via direct bank transfer. Max ₹4,000 per partner.",
    featured: true,
    userProgress: 0,
    unlocked: false,
  },
  {
    id: "off-diya",
    title: "Diya Milestone Gift",
    subtitle: "5 Qualifying Paid Clients",
    badgeText: "20 SLOTS",
    description: "Unlock a ₹3,000 Amazon shopping voucher plus official Retner Partner Circle badge & listing once 5 referred clients complete their 2nd quarterly payment.",
    heroImage: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&auto=format&fit=crop&q=80",
    rewardType: "voucher",
    rewardName: "₹3,000 Amazon E-Voucher",
    rewardValuePaise: 300000,
    targetCount: 5,
    targetStatus: "paid",
    windowOnly: true,
    startAt: "2026-09-01T00:00:00Z",
    endAt: "2026-12-31T23:59:59Z",
    status: "live",
    eligibleTiers: ["tier-gold", "tier-platinum"],
    terms: "Limited to 20 partners in order of qualification. Requires 2nd quarterly payment cleared. Non-stackable.",
    featured: true,
    userProgress: 0,
    unlocked: false,
  },
  {
    id: "off-lantern",
    title: "Lantern Milestone Gift",
    subtitle: "10 Qualifying Paid Clients",
    badgeText: "4 SLOTS",
    description: "Unlock a ₹15,000 Amazon shopping voucher plus an exclusive co-branded case study feature published across Retner official channels.",
    heroImage: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&auto=format&fit=crop&q=80",
    rewardType: "voucher",
    rewardName: "₹15,000 Amazon E-Voucher + Feature",
    rewardValuePaise: 1500000,
    targetCount: 10,
    targetStatus: "paid",
    windowOnly: true,
    startAt: "2026-10-01T00:00:00Z",
    endAt: "2026-12-31T23:59:59Z",
    status: "live",
    eligibleTiers: ["tier-platinum"],
    terms: "Limited to 4 partners in order of qualification. Requires 2nd quarterly payment cleared. Voucher delivered via WhatsApp/Email within 15 days.",
    featured: true,
    userProgress: 0,
    unlocked: false,
  },
  {
    id: "off-firework",
    title: "Firework Milestone Gift",
    subtitle: "15 Qualifying Paid Clients",
    badgeText: "2 SLOTS",
    description: "Unlock a ₹15,000 Amazon Voucher plus dedicated VIP priority support line and VIP early access to all new Retner AI features.",
    heroImage: "https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80",
    rewardType: "voucher",
    rewardName: "₹15,000 Amazon Voucher + VIP Support",
    rewardValuePaise: 1500000,
    targetCount: 15,
    targetStatus: "paid",
    windowOnly: true,
    startAt: "2026-10-01T00:00:00Z",
    endAt: "2026-12-31T23:59:59Z",
    status: "live",
    eligibleTiers: ["tier-platinum"],
    terms: "Limited to 2 partners in order of qualification. 30% first-year revenue cap applies. Highest milestone awarded.",
    featured: false,
    userProgress: 0,
    unlocked: false,
  }
];

export const initialSettings: ProgramSettings = {
  attributionWindowDays: 60,
  leadProtectionDays: 90,
  autoApprovePartners: false,
  defaultHoldDays: 30,
  minPayoutPaise: 100000,
  maxOpenPayouts: 1,
  tdsRatePercent: 5.0,
  tdsAnnualThresholdPaise: 1500000,
  notificationAlertEmails: ["partners@retner.ai", "finance@retner.ai"],
  campaignStartAt: "2026-10-01T00:00:00Z",
  campaignEndAt: "2026-12-31T23:59:59Z",
  qualifyingPlans: ["₹2,999/mo (Diwali Special)", "₹3,500/mo (Standard Growth)", "Enterprise Custom Plans"],
};

// Clean initial data (No hardcoded dummy records)
export const initialPartners: Partner[] = [];
export const initialLeads: Lead[] = [];
export const initialEarnings: Earning[] = [];
export const initialPayouts: PayoutRequest[] = [];
export const initialRewardClaims: RewardClaim[] = [];
export const initialAuditLogs: AuditLog[] = [];
